### ISSUE TITLE
protoc protoc-gen-grpc-web 2个工具能支持windows吗

### ISSUE THREAD

**Issue by sitsh** [11os/grpc-mp#1]
protoc 和 protoc-gen-grpc-web 2个工具能支持windows吗
没有mac 环境 生成 _pb.js 
或者能自己编译这2个工具成winsows版本？

**Comment by 11os** [comment]
可以自己编的，我只改了源码其余编译配置都是官方的，不过看windows环境配置还挺麻烦我还没试过

**Comment by sitsh** [comment]
好的 知道了。期待有 linux 或 win 的二进制版本

**Comment by sitsh** [comment]
😀， 不好意思又来提问了， 我在 linux 下成功编译了 protoc 和 web plug  生成了 pb.xxx.js
在微信 小程序 项目中 不会使用他们。如果想 grpc-web helloword 中使用他们会报错。
因为前端不是太熟悉。能不能 稍微说下 小程序项目中 如果使用他们 调用 grpc 端点

我的使用步骤是
新建小程序项目
根目录 npm -i  grpc-mp --production
npm install
小程序 开发工具 构建npm

page/index.js

//index.js
//获取应用实例
const app = getApp()


const { HelloRequest, HelloReply } = require('./helloworld_pb.js'); //生成的
const { GreeterClient } = require('./helloworld_grpc_web_pb.js'); //生成的

Page({

  //事件处理函数
  bindViewTap: function() {

  },
  onLoad: function () {

  },
  grpcGet: function(e) {
    console.log(e)
    /*
    var client = new GreeterClient('https://grpc.wecail.com',
      null, null);

    var request = new HelloRequest();
    request.setName('World');

    client.sayHello(request, {}, (err, response) => {
      console.log(response.getMessage());

    });
*/
  }
})




hao.zhong <notifications@github.com> 于2019年5月25日周六 上午9:35写道：
